sudo: required
language: node_js
cache: google-cloud-sdk
node_js:
- '6.9'
services:
- docker
env:
  global:
  - secure: ZQdhm+98vkPDXaAD4BBp8gNBo0mmFkEtsYyNBL/kNODmufUSTpy/c7g3kPmqVexlJLv5Mil7Lr0HruDSYPC9F9ZO+jhMbqvITnCXRpDGFAHgR2ffI1vflVhUaLgRvwxE6X4QukjlCjJZhWTRuKB88qoivwe+vRkcHnesNCi3BCgUr3kvBRvFseRdlFJ1Er7tTmyORjjQ2JKrgprVXStqAGqU8Z4Xa3ixvCwfssfB6NVHMTk2CsnfhljdrZeZAm+QAOrBy0ZajpXyaCDTQnWwuKCgeF5ARnscSKQlOzRgEHwZPKODe8FJvsZ0H0uV437L7u4EYMEjeh+r1E3QNCvnGkMIoBvFYYd71UUbmyoIzwu7ogj8H9PenIgzAF4FeTPOb97SBaZJSDkA0A1ZrbK1Q2gHRK2lbOM/F8HDYf+AtlNeLXIKfY2Ld5rixDD+q0ABzwOoZVxLCQYmwgVwzSGaRgTMSay1CbfbkMynGx4aOR/5N8RkqR6tIs2m7+l4NWdopWLaYaABh65NnaV6nKokA4n097hS+zFzu3ihixLqfkWtftvONQFQ2X+eLcdmE09bG4XtIzT1GBr0zuHgnbS/tPeJQC8h7j/SgagyX7NCk4JYHpsJPdE5Wbi/3aqlo9lcoLbu5hl9zzeXvc+77UHITJjxx6IgkfoiS5/n7FLcSjM=
  - secure: t6qfRGFJGyonF2At/XouVyXWDt2xPN+VCK/jBNCW9r7oDjSO8JNuacK/fXOWlFWQhwp6jS9cyokUQjIy97I0BUDLyVHG4mlqEH9yKlUdY9EBWc0aeNORC/5/lzr0q/7wZJhdu+yvF5khfbAo01FiOMnh5BukM1fV6laqEa9OFs+GRAsIgTu0w6jgGh2QuNHmOo2L6kHQQvc2W4qTMk5Ce/z3DFEH+WlXTNd2ag1+IVzhc3QUlXGxdOxXwzYTYheLLWKnu/ClhsK8oDfdCQE6BHWENRO/F5y3bcvMbOQMoOsT9fULf5c3w8MYPY4Y7W7if1WFoWKPFWHt4LLcdenGiOMKmcfskgoBfqgSvq1T9C+VPg6wGQyQECFHX44U/eFzo2K7o7oP9bcLDG7IKE/P+1SFaFH7NBzfcoSYOfMNEslSPTLL424jocrZLIWsB6F8NfXLdTeOjP/XEDSWZ0nITeaqi2Od3/1GpcekPTTWP3Wkz+UCxeC4jqDpnk4YjohHXo8K1v++fdOGMCsIvoFyZgtvr1Hsiycxl4qYA6iCYGhyZ1mXHgpL8J1xsM6WXAVRNhuvgFRZvyYPlYtD0mKSEflsLh5EaeBWnJn1sJWOBoIh7BGsvYwklutIBYJRckTiJ1Z2lyTyivXgWKmcUGtO3lSI0wS5oknF3SIjn5ORrDU=
  - secure: R4oBuY7ag5grp3Mq6cgjTWzH9azPEXs+Pt/vhhaaK6sta+wn1MKspHrz6mrNuzMIh1/NonhLFHZkQsLgYKi9r5hHnjurXJmT7RzIC5eOBj9Zg3PDba0dV6sdE6IIpxzWPQp8yNdAm2QNXBCKGXl9E5x+VuxD+88slMbfvvakqe/XLHCtV6gJ84sMBBmIHpuCV++9h4u8yZ/Jb6OfZYMGmFjTgy8coLMz8VyHrQ1GMr/x6gqOgYulBDXHVhHHoVl1EH2pBtDYqcx3kA53g7BpgwyO96MpQlZV6eR669fzjKkIJlwYqW2PSOxT0VxnePk8gjKtMq/EeklT1p+ujQZUuM8G95K37dx5u5T9B3HFYjZ2jrLwzf0k7NDmNnLA1zmGf4fVfCvWvZ31xMlXprbj5z4T8cnwBmPwZBGbH5ASCuCU44Hd9czmQdOTCtFEvXQIjoOBzPENBGThuzk+Wi3zin3tsbVQ/JQcOOknG3HvaqO4teDAuphMc7ZwBOhIqMyIR7UM4CAy/1YOAmc1oYea3HlaQm6wLa39HSbafMFPg/mwCURRiCyXwStBH7JVFtXNlZ5ChbVmMxWjRT96g89VsZFCTF/vb3ncMZ1OWhSIDo3MQNyVAM55OREpm3spTcVYGiDXdNsGAcQx4m4lsY8tphidUqJFI1f8rtZz4Yw7gzU=
  - COMMIT=${TRAVIS_COMMIT::8}
script:
- echo 'tested'
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export KUBE_APP_NAME=nrw-freigegeben
- export REPO=schurig/nrw_freigegeben
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
- curl https://gist.githubusercontent.com/schurig/ddfc188bbf4c6a3f67d6a9fe9cf3c690/raw/travis_ci_gcloud_prepare.sh | sh
- export PATH=./google-cloud-sdk/bin:$PATH
- kubectl --kubeconfig ./kubernetes-config.json patch deployment $KUBE_APP_NAME -p '{"spec":{"template":{"spec":{"containers":[{"name":"nrw-freigegeben","image":"'$REPO':'"$COMMIT"'"}]}}}}'
before_install:
- openssl aes-256-cbc -K $encrypted_6e7d3f7c2fe4_key -iv $encrypted_6e7d3f7c2fe4_iv
  -in kubernetes-config.json.enc -out kubernetes-config.json -d
